### ISSUE TITLE
timestamp bad pattern

### ISSUE THREAD

**Issue by david85fr** [jamesbattersby/vscode-loginterleaver#178]
It doesn't work with this pattern:
**[**2021-01-26 09:50:32.0**]** kernel: <INFO> EXT4-fs abcdef....

Problem seems comes from  '[' and ']'

**Comment by david85fr** [comment]
I tried to prefix regex with (?:\[?) , without success

**Comment by jamesbattersby** [comment]
Could you give the regex that you've tried so far.

**Comment by david85fr** [comment]
> Could you give the regex that you've tried so far.
I've tried:
^(\[?[\d]{4}[-\/][\d]{2}[-\/][\d]{2}[\sT]{1}[\d]{2}:[\d]{2}:[\d]{2}(?:[\.,]{1}\d*)?(?:Z)?(?:(?<!Z)[\+-]{1}[\d]{2}:[\d]{2})?)
^((\[?)[\d]{4}[-\/][\d]{2}[-\/][\d]{2}[\sT]{1}[\d]{2}:[\d]{2}:[\d]{2}(?:[\.,]{1}\d*)?(?:Z)?(?:(?<!Z)[\+-]{1}[\d]{2}:[\d]{2})?)
^((?:\[)?[\d]{4}[-\/][\d]{2}[-\/][\d]{2}[\sT]{1}[\d]{2}:[\d]{2}:[\d]{2}(?:[\.,]{1}\d*)?(?:Z)?(?:(?<!Z)[\+-]{1}[\d]{2}:[\d]{2})?)
^((?:\[?)?[\d]{4}[-\/][\d]{2}[-\/][\d]{2}[\sT]{1}[\d]{2}:[\d]{2}:[\d]{2}(?:[\.,]{1}\d*)?(?:Z)?(?:(?<!Z)[\+-]{1}[\d]{2}:[\d]{2})?)

**Comment by jamesbattersby** [comment]
I think the expression you need is:

`^\[?([\d]{4}[-\/][\d]{2}[-\/][\d]{2}[\sT]{1}[\d]{2}:[\d]{2}:[\d]{2}(?:[\.,]{1}\d*)?(?:Z)?(?:(?<!Z)[\+-]{1}[\d]{2}:[\d]{2})?)\]?`

The square brackets are special characters so need to be escaped, and need to be outside of the capture.  Please let me know if this works for you.

**Comment by jamesbattersby** [comment]
I'm going to assume this is resolved.
