### ISSUE TITLE
[Feature request] Progress indication

### ISSUE THREAD

**Issue by mevolution** [jamesbattersby/vscode-loginterleaver#425]
Would be super nice when opening larger files, it can take up to one minut to merge larger files and there is no indication that Vscode is working or what progress the plugin have. 
I don't mind waiting as long as I know that it's coming :-)

Thanks for a beautiful plugin

**Comment by jamesbattersby** [comment]
Thanks for this.  Out of interest what size files are you working with?

**Comment by mevolution** [comment]
They range from 0,5MB to up to 100MB, mostely around 5MB size and I would like to open 3-5 of them

**Comment by mevolution** [comment]
The two other things that are high on the wishlist os to be able to:
1. restrict the log in time like "last 5 minutes" 
2. hot  reload of the files (like tailing) to be able to tail the logs restricted to say 3-5 minutes and be able to pause when something happens

**Comment by jamesbattersby** [comment]
A progress indicator has been added.  You should also find that it is a bit quicker now.
