### ISSUE TITLE
Allow to parse more timestamps

### ISSUE THREAD

**Issue by nicofrand** [jamesbattersby/vscode-loginterleaver#485]
Hi,

thanks for the nice extension!

I have some logs with date & time that cannot be parsed with moment or `Date()` such as

```
[19/Apr/2023:01:10:14 +0000]  ------------------
```

My regex is `^\[(\d{2}\/\w+\/\d{4}:\d{2}:\d{2}:\d{2})` but that is not a valid date format.

Would there be some way to either use lexical order as a fallback?
Or give a way to transform the value of the regex in a parsable format (ex: ISO). In this case I don't care about the month so I could rewrite it to "04" or something with regex substitution…

Thanks in advance for your point of view.

**Comment by jamesbattersby** [comment]
I'll have a think about the best way to allow this.
