### ISSUE TITLE
extension stopped working, can't parse timestamp

### ISSUE THREAD

**Issue by yriouvortex** [jamesbattersby/vscode-loginterleaver#556]
Hi, 
I worked previously with the extension without any problem, but one day, it just stopped interleaving my logs. 

Here is the logs type that I want to parse : 
INFO :2023/10/02 09:24:06.557501 vtxapp.go:1109:  Check Alert !

Here is the regexp that I am using : https://regex101.com/r/OCgrZe/1
(?:.*)(\d{4}\/\d{2}\/\d{2} \d{2}:\d{2}:\d{2}\.\d+)

Here is the settings of the extension : 
```
 {
   "loginterleaver.timeFormatSpecifications": [
    
        
        {
            "name": "My time format",
            "format": "yyyy/LL/dd HH:mm:ss.SSSSSS"
        }
        
    ],
    "loginterleaver.timestampRegex": "(?:.*)(\\d{4}\\/\\d{2}\\/\\d{2} \\d{2}:\\d{2}:\\d{2}\\.\\d+)",
    "loginterleaver.dropBlankLines": false,
    "loginterleaver.dropInvalidTimestamp": true,
}
```
When I ran the extension, I choose several logs file, it spins for a few seconds and then nothing happen. 

I think it has something to do with the parsing of the timestamp but I can manage to find what is the problem. 

Regards,

**Comment by anderslars** [comment]
I have the same issue. extension just spins saying 'loading files' even with sample small log file with lines matching regex. Cheers

**Comment by jamesbattersby** [comment]
Hi, the problem is that there is a space in your regex.  Multiple regular expressions are now supported and a space is the separator, so it is seeing this as two expressions.  Below is an updated regex that should work for you.

`"(?:.*)(\\d{4}\\/\\d{2}\\/\\d{2}\\s\\d{2}:\\d{2}:\\d{2}\\.\\d+)"`

Please let me know if this resolves your issue.

**Comment by yriouvortex** [comment]
Thanks for the quick reply. I understand now about the space problem.
The regex that you provided works perfectly when added directly in the json file (or **(?:.*)(\d{4}\/\d{2}\/\d{2}\s\d{2}:\d{2}:\d{2}\.\d+)** added in the "Settings GUI" of the extension. 

Regards
